platform :ios, '12.0'

target 'TGSubmodoulesDemo' do

  use_frameworks!

  pod 'TGSubmodoules/Display', :path => '../'
#  pod 'TGSubmodoules/PresentationData', :path => '../'
#  pod 'TGSubmodoules/UIKitRuntimeUtils', :path => '../'
#  pod 'TGSubmodoules', :path => '../'

end
